version: '3.8'

services:
  web:
    image: your-dockerhub-username/express-mongodb-app:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=staging
      - MONGODB_URI=mongodb://mongo:27017/expressdb
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:6.0
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo_staging_data:/data/db
    restart: unless-stopped

volumes:
  mongo_staging_data: 