apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-postgres-app
  labels:
    app: flask-postgres-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-postgres-app
  template:
    metadata:
      labels:
        app: flask-postgres-app
    spec:
      containers:
      - name: flask-app
        image: ghcr.io/your-username/flask-postgres-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: DATABASE_URL
          value: "postgresql://postgres:postgres@postgres-service:5432/flaskdb"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: flask-postgres-app-service
spec:
  selector:
    app: flask-postgres-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: LoadBalancer 